### ISSUE TITLE
Explore PowerDNS to Replace Unbound DNS

### ISSUE THREAD

**Issue by carpenike** [carpenike/k8s-gitops#8]
https://www.disasterproject.com/powerdns-overkubernetes-helm-v3/

Potential to use https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/pdns.md with service annotation to auto-register DNS names:

```
apiVersion: v1
kind: Service
metadata:
  name: echo
  annotations:
    external-dns.alpha.kubernetes.io/hostname: echo.example.com
spec:
  selector:
    app: echo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
```
